graphviz: Autospec creation for update from version stable.2.42.2 to version 2.44.0
CristiFati (1):
      [Issue #1481]: MSB4018 The NativeCodeAnalysis task failed unexpectedly.

Emden R. Gansner (1):
      Improve warning message in color list for case when user uses semicolor rather than color to

Henrik Grimler (4):
      lib/gvpr: compile mkdefs with $(HOSTCC) rather than $(CC)
      lib/cgraph: include empty malloc.h from subdir include
      lib/sfdpgen: include malloc.h in PriorityQueue.c to define free
      lib/vpsc: rename bcopy->b_copy

Jannick (2):
      tred: remove trailing white spaces
      tred: add option to output information on removed edges to stderr

John Ellson (31):
      Stable Release 2.42.3
      why can't appveyor use my version number automatically???
      Move back to 2.43 development series
      clang doesn't support -fstack-clash-protection
      use "" instead on <> for non-system includes
      cleanup a [-Wparentheses]
      more [-Wparentheses]
      fc32 + swig + ocaml issue:  gv_ocaml.cpp:1362:48: error: invalid conversion from ‘const caml_value_t*’ {aka ‘const long int*’} to ‘caml_value_t*’ {aka ‘long int*’} [-fpermissive]
      add shapes.py. vuln.py to tar.gz distribution
      trying to fix .md5 generation during deployment
      remove unneeded dependency that was preventing smyrna in rpm distros
      adding D and JAVASCRIPT lang bindings - currently disabled
      setting up for LAND_D and LANG_JAVASCRIPT rpms
      fix centos[67] breakage
      SUSE maintainer
      ignore more products
      start fc33 builds, stop fc227, fc28
      fix for python version churn on .el8
      start centos8 builds
      add '#ifdef __cplusplus' wrapper to sgd.h to try to fix windows build error
      add sgd.[ch] to vxproj files
      add randomkit.[ch] to vcxproj files
      disable Ubuntu18-10 builds - EOL
      manually set reasonable version number in CMakeLists.txt
      update ChangeLog to show merging activity
      CMakeLists.txt versioning again ...
      Revert "Merge branch 'Grimler/graphviz-malloc.h-problem'"
      Revert "Revert "Merge branch 'Grimler/graphviz-malloc.h-problem'""
      try removing recently added  in lib/gvc/CMakeLists.txt
      Revert "try removing recently added  in lib/gvc/CMakeLists.txt"
      try adding  to lib/pathplan/CMakeLists.txt

Jonathan Zheng (19):
      first working version
      removed unnecessary print
      verbosity added. nodes can be pinned but shortest paths still calculated for every node TODO
      pinned nodes working
      fixed indentation
      fixed more indentation
      made dijkstra clearer
      randomkit is good but not worth. Other optimizations needed
      randomkit added
      dijkstra is now fast!
      undid changes to types.h
      added subset model
      ignored multiedges in subset model
      fixed initial_positions segfault
      removed some comments
      fixed indentation
      updated documentation
      fixed weighted shortest paths calculation
      removed MODEL_MDS for now

Magnus Jacobsson (31):
      Remove SVG title for anonymous graphs
      Fix lintian errors appearing when running in Docker
      Add Dockerfile for Ubuntu 18.04
      Add Dockerfile for Ubuntu 19.04
      Add Dockerfile for Ubuntu 19.10
      XML-escape xlink:href attribute in SVG
      Run portable-source in docker on gitlab runner
      Build Ubuntu 18.04 & 19.04 in Docker containers on GitLab runners
      Add building of Ubuntu 19.10 in Docker container on GitLab runner
      Add FIXME about Ubuntu 18.10 not run in docker on gitlab runner
      Output OS release info to stdout
      Add Dockerfile for Centos 8
      Update Dockerfile for Centos 7 with needed prerequisites
      Add Dockerfile for Centos 6
      Build for Centos 6, 7 & 8 in Docker containers on GitLab runners
      Use ${HOME} to access rpm build directory
      Add Dockerfile for Fedora 33
      Add Dockerfile for Fedora 32
      Add Dockerfile for Fedora 31
      Add Dockerfile for Fedora 29
      Remove out-commented stuff from centos6/Dockerfile
      Build for Fedora 29, 30, 31, 32 & 33 in Docker containers on GitLab runners
      Run private runner locked Ubuntu 18.10 only on upstream
      Run deploy stage only on upstream
      Add helpers and reference files for shapes test to dist
      Add input and reference files for vuln test to dist
      Add input and reference files for rtest to dist
      Stable Release 2.42.4
      Move back to 2.43 development series
      Don't build anything for tags
      Stable Release 2.44.0

Mark Jason Dominus (陶敏修) (3):
      ignore more products
      ignore more products
      Correct description of 'port' syntax in manual

Mathis Beer (1):
      Work around issue 1671: avoid creating a virtual edge loop.

Nathan Owens (1):
      Add pkg-config files

Nikita Ermakov (1):
      Add riscv64 to host_cpu configure.ac

Stephen C North (8):
      stable release 2.42.2
      Fix graphviz out-of-source build per https://gitlab.com/graphviz/graphviz/issues/1596
      Move back to development version and fix documentation to warn regarding HTML labels within record shapes.
      Revert "I think this fixed something wrong with scale."
      Note that showboxes is only TB mode!
      Attempted fix for https://gitlab.com/graphviz/graphviz/issues/1631
      Adds feature for graph postaction setting
      an assert in applyattrs() is too restrictive when setting edge [key=something}

Stephen C. North (2):
      Update README.md
      Update README.md

jxz12 (1):
      first test

zhangjialing (1):
      host_cpu add mips64 platform